author: Wilfried Woivré
name: Wilfried Woivré & Azure
description: Blog personnel de Wilfried Woivre parlant des sujets Azure, Cloud, Serverless, Container, ...

title: Wilfried Woivré
subtitle: Cloud Solution Architect - MVP Microsoft Azure

url: "https://woivre.fr"

baseurl: ""

github: "wilfriedwoivre"

twitter_username: "wilfriedwoivre"
linkedin_username: "wilfriedwoivre"

gaaccount: UA-12469243-2

comments: false

isso: ''
disqs: ''

urls:
    - text: Home
      url: /
      target: _self
    - text: Archives
      url : /archive.html
      target: _self
    - text: About Me
      url: /about.html
      target: _self
    - text: RSS
      url : /feed.xml
      target: _blank
    - text: Github
      url: https://github.com/wilfriedwoivre
      target: _blank

permalink: '/:year/:month/:title'

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      permalink: '/blog/:year/:month/:title'
      title: 'Wilfried Woivré & Azure - :title'

paginate: 12

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

exclude: ['utils', 'README.md', 'LICENSE']